
name: Test GitHub Actions
on:
  push:
    branches: [ main, action ]
  pull_request:
    branches: [ main, action ]
  repository_dispatch:
    types: [opened, deleted, scan_completed, completed, hello, bye]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "${{ toJson(github.event) }}"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Hola
        if: ${{ github.event.action == 'hello' }}
        run: npx cowsay "Hola!"
      - name: Adiós
        if: ${{ github.event.action == 'bye' }}
        run: npx cowsay "Adiós!
      - name: Report
        if: ${{ github.event.action == 'scan_completed' }}
        run: echo check out "${{ toJson(github.event.client_payload) }}"
        
        
        
        
